import streamlit as st
import os
import sys
from typing import Dict, Any

# --- CRITICAL: Add supervisor_agent directory to Python path ---
PROJECT_ROOT = os.path.dirname(os.path.abspath(__file__))
SUPERVISOR_PATH = os.path.join(PROJECT_ROOT, "supervisor_agent")

if SUPERVISOR_PATH not in sys.path:
    sys.path.append(SUPERVISOR_PATH)

# --- Import Supervisor Builder ---
from supervisor import SupervisorAgentBuilder, create_initial_overall_state

# --- Build and Compile Graph Once ---
AGENT_BUILDER = SupervisorAgentBuilder()
GRAPH_APP = AGENT_BUILDER.build()

# --- STREAMLIT SESSION STATE MANAGEMENT ---
if "chat_state" not in st.session_state:
    st.session_state.chat_state = create_initial_overall_state()

    st.session_state.messages = []
    initial_greeting = (
        "👋 Hello! I'm your post-discharge care assistant. Could you please tell me your name?"
    )
    st.session_state.messages.append({"role": "system", "content": initial_greeting})

# --- Utility: Agent Icons ---
def get_agent_icon(agent_name: str) -> str:
    if not agent_name:
        return "🤖"
    name = agent_name.upper()
    if "RECEPTIONIST" in name:
        return "👩‍💼"
    elif "CLINICAL" in name:
        return "⚕️"
    elif "SUPERVISOR" in name:
        return "🧠"
    elif "USER" in name:
        return "🧑"
    return "🤖"

# --- UI Header ---
st.title("🏥 Post-Discharge Medical Assistant")
st.caption("Architecture: Supervisor Router → [Receptionist | Clinical]")

# Display patient name directly from state (not inside context anymore)
display_name = st.session_state.chat_state.get("patient_name", "Not identified")
st.subheader(f"Current Patient: {display_name}")

# --- Display Conversation ---
for message in st.session_state.messages:
    role = message["role"]
    avatar = get_agent_icon(role)
    display_role = "assistant" if role != "user" else "user"

    with st.chat_message(display_role, avatar=avatar):
        st.markdown(message["content"])

# --- User Input ---
if prompt := st.chat_input("Ask about your recovery, or start by introducing yourself..."):
    # 1️⃣ Add user message
    st.session_state.messages.append({"role": "user", "content": prompt})
    with st.chat_message("user", avatar=get_agent_icon("USER")):
        st.markdown(prompt)

    # 2️⃣ Update current state
    current_state = st.session_state.chat_state
    current_state["input"] = prompt
    current_state["history"].append({"role": "user", "content": prompt})

    # 3️⃣ Invoke LangGraph (Supervisor → Receptionist/Clinical → END)
    with st.spinner("Routing via Supervisor Agent..."):
        try:
            final_state = GRAPH_APP.invoke(current_state)
            final_response = final_state.get(
                "output", "⚠️ No response generated by the agent."
            )
            final_agent = final_state.get("agent", "SYSTEM")
            st.session_state.chat_state = final_state
        except Exception as e:
            final_response = f"🚨 Error during agent processing: {e}"
            final_agent = "ERROR"
            st.error(e)

    # 4️⃣ Display Agent Reply
    with st.chat_message("assistant", avatar=get_agent_icon(final_agent)):
        st.markdown(final_response)

    # 5️⃣ Save message in history and refresh UI
    st.session_state.messages.append({"role": final_agent, "content": final_response})
    st.rerun()
